import Head from 'next/head';

import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					React Query Pagination and Infinite Queries with NextJs
				</h1>
				<br />
				<h2>Pagination CSR</h2>
				<Link href={`/paginationCSR?page=${1}`}>Pagination CSR</Link>
				<br />
				<h2>Pagination CSR 2</h2>
				<Link href={`/paginationCSR2`}>Pagination CSR</Link>
			</main>
		</div>
	);
}
